[alias]
today = "run --quiet --release --features today -- today"
scaffold = "run --quiet --release -- scaffold"
download = "run --quiet --release -- download"
read = "run --quiet --release -- read"

solve = "run --release -F unsafe_optimizations -- solve"
solve_safe = "run --quiet --release -- solve"
all = "run --quiet --release -F unsafe_optimizations -- all"
all_safe = "run --quiet --release -- all"
time = "run --quiet --release -F unsafe_optimizations -- time"
time_safe = "run --quiet --release -- time"

[env]
AOC_YEAR = "2025"
